apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: voting-app-vote-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
      name: voting-app-vote
    spec:
      containers:
        - name: voting-app-vote-container
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
              name: vote