apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: voting-app-vote-service
spec:
  type: NodePort
  selector:
    app: vote
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31000
      