apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: worker
  name: voting-app-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: voting-app-worker-container
          image: dockersamples/examplevotingapp_worker
          