apiVersion: v1
kind: Pod
metadata:
  labels:
    app: db
  name: voting-app-db
spec:
  containers:
    - name: voting-app-db-container
      image: postgres:15-alpine
      ports:
        - containerPort: 5432
          name: postgres
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
  volumes:
    - name: db-data
      emptyDir: {}
