apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: voting-app-db-service
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
      name: "db-service"
