apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: voting-app-redis-service
spec:
  type: ClusterIP
  selector: 
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: "redis-service"
    